import { StyleSheet } from 'react-native';

// Dark, low-glare theme: black background, soft light text, muted green accents.
export const INK = '#d6ddd8';
export const MUTED = '#7d8981';
export const GREEN = '#3a8f68';
export const PAPER = '#000000';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#000000', alignItems: 'center' },
  // Holds the current screen between the brand bar and the bottom bar.
  stack: { flex: 1 },
  appFrame: { flex: 1, width: '100%', maxWidth: 560, backgroundColor: PAPER, paddingTop: 48 },
  appFrameCompact: { paddingTop: 38 },
  topline: { height: 46, marginHorizontal: 23, flexDirection: 'row', alignItems: 'center' },
  brandLogo: { width: 34, height: 34, borderRadius: 8 },
  brand: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  brandCopy: { marginLeft: 10, flex: 1 },
  brandName: { color: INK, fontSize: 12, fontWeight: '800', letterSpacing: 1.25 },
  brandSub: { color: MUTED, fontSize: 8, fontWeight: '700', marginTop: 3 },
  avatar: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: '#26302b', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: INK, fontSize: 10, fontWeight: '800' },
  avatarSignedIn: { backgroundColor: GREEN, borderColor: GREEN },
  avatarTextSignedIn: { color: '#e6ece8' },
  weightField: { flexDirection: 'row', alignItems: 'center', marginLeft: 6 },
  weightInput: { width: 48, height: 34, borderWidth: 1, borderColor: '#26302b', borderRadius: 6, textAlign: 'center', color: INK, fontSize: 13, fontVariant: ['tabular-nums'], backgroundColor: '#101412' },
  weightUnit: { color: MUTED, fontSize: 10, fontWeight: '700', marginLeft: 4 },
  latestCopy: { flex: 1, paddingVertical: 6, marginRight: 8 },
  newCourseButton: { marginTop: 0 },
  layoutMapCopy: { paddingVertical: 10 },
  stepDots: { flexDirection: 'row', marginBottom: 16 },
  stepDot: { flex: 1, alignItems: 'center' },
  stepDotMark: { width: '90%', height: 4, borderRadius: 2, backgroundColor: '#26302b' },
  stepDotMarkDone: { backgroundColor: GREEN },
  stepDotLabel: { color: MUTED, fontSize: 7, fontWeight: '800', letterSpacing: 0.6, marginTop: 5 },
  stepDotLabelCurrent: { color: INK },
  statsSection: { marginTop: 8, marginBottom: 18 },
  statsHeading: { color: INK, fontFamily: 'Georgia', fontSize: 15, marginTop: 14, marginBottom: 6 },
  statsChips: { color: MUTED, fontSize: 11, lineHeight: 17 },
  statsToggle: { marginTop: 4 },
  statTable: { borderRadius: 8, borderWidth: 1, borderColor: '#26302b', overflow: 'hidden', marginBottom: 4 },
  statTableRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7, paddingHorizontal: 8, borderTopWidth: 1, borderTopColor: '#1b2420' },
  statTableHead: { backgroundColor: '#141816', borderTopWidth: 0 },
  statHeadText: { color: MUTED, fontSize: 7, fontWeight: '800', letterSpacing: 0.6 },
  statCellName: { flex: 1.6, color: INK, fontSize: 11, fontWeight: '700' },
  statCell: { flex: 1, color: INK, fontSize: 11, textAlign: 'right', fontVariant: ['tabular-nums'] },
  caddieRow: { borderTopWidth: 1, borderTopColor: '#26302b', marginTop: 6, paddingTop: 6 },
  caddieText: { color: INK, fontSize: 13, fontWeight: '700', marginTop: 3 },
  caddieMeta: { color: MUTED, fontSize: 11, fontWeight: '400' },
  authIntro: { color: MUTED, fontSize: 11, lineHeight: 16, marginBottom: 8 },
  authNotice: { color: GREEN, fontSize: 11, lineHeight: 16, marginBottom: 8 },
  codeInput: { fontSize: 20, letterSpacing: 6, fontVariant: ['tabular-nums'] },
  textLink: { alignSelf: 'center', paddingVertical: 10, marginTop: 4 },
  textLinkText: { color: GREEN, fontSize: 12, fontWeight: '700' },
  resumeButton: { marginTop: 0, marginBottom: 12 },
  throwRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 3 },
  throwRowText: { flex: 1 },
  throwEditHint: { color: GREEN, fontSize: 7, fontWeight: '800', letterSpacing: 0.6, marginLeft: 8 },
  editFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 18 },
  editFooterActions: { flexDirection: 'row' },
  saveButton: { backgroundColor: GREEN, borderColor: GREEN, marginLeft: 8 },
  saveButtonText: { color: '#e6ece8', fontSize: 12, fontWeight: '800' },
  toggleRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6, marginBottom: 10, padding: 12, borderRadius: 8, backgroundColor: '#101412', borderWidth: 1, borderColor: '#26302b' },
  toggleCopy: { flex: 1, marginRight: 12 },
  toggleAction: { alignSelf: 'flex-start', marginTop: 0, marginBottom: 16 },
  authTabs: { marginTop: 0, marginBottom: 12 },
  authError: { color: '#d07a68', fontSize: 10, lineHeight: 15, marginTop: 10 },
  accountStatus: { color: INK, fontFamily: 'Georgia', fontSize: 17, marginTop: 6, marginBottom: 4 },
  serverNote: { color: '#6b766f', fontSize: 7, fontWeight: '700', letterSpacing: 0.6, marginTop: 24, textAlign: 'center' },
  backLink: { alignSelf: 'flex-start', paddingVertical: 6, marginBottom: 8 },
  pageHeadingCompact: { marginTop: 4, marginBottom: 0, justifyContent: 'flex-end' },
  pageHeading: { marginHorizontal: 23, marginTop: 28, marginBottom: 19, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' },
  // The eyebrow and title wrap rather than push the back button off screen (long course names).
  headingCopy: { flex: 1, marginRight: 12 },
  eyebrow: { color: GREEN, fontSize: 9, fontWeight: '800', letterSpacing: 1.2 },
  title: { color: INK, fontFamily: 'Georgia', fontSize: 30, marginTop: 5 },
  weather: { flexDirection: 'row', alignItems: 'center', marginBottom: 5 },
  weatherIcon: { fontSize: 14, color: '#d38244', marginRight: 4 },
  weatherText: { color: MUTED, fontSize: 8, fontWeight: '800' },
  homeButton: { flexShrink: 0, borderWidth: 1, borderColor: '#26302b', paddingHorizontal: 11, paddingVertical: 8, borderRadius: 6 },
  homeButtonText: { color: GREEN, fontSize: 9, fontWeight: '800', letterSpacing: 0.5 },
  content: { paddingHorizontal: 23, paddingTop: 15, paddingBottom: 20 },
  menuIntro: { backgroundColor: '#0f1a14', borderRadius: 9, padding: 18, marginTop: 1, marginBottom: 17 },
  menuIntroLabel: { color: GREEN, fontSize: 8, fontWeight: '800', letterSpacing: 1 },
  menuIntroTitle: { color: INK, fontFamily: 'Georgia', fontSize: 21, marginTop: 8 },
  menuIntroCopy: { color: MUTED, fontSize: 10, marginTop: 5 },
  menuOptions: { borderTopWidth: 1, borderTopColor: '#26302b' },
  menuItem: { minHeight: 76, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#26302b', paddingHorizontal: 5 },
  resumeItem: { marginTop: 0, marginBottom: 14 },
  menuItemPrimary: { backgroundColor: GREEN, borderBottomColor: GREEN, paddingHorizontal: 12, marginTop: 9, borderRadius: 7 },
  menuNumber: { color: '#6b766f', fontSize: 10, fontWeight: '800', width: 37 },
  menuNumberPrimary: { color: '#bcd2c0' },
  menuItemCopy: { flex: 1 },
  menuTitle: { color: INK, fontFamily: 'Georgia', fontSize: 17 },
  menuTitlePrimary: { color: '#e6ece8' },
  menuSubtitle: { color: MUTED, fontSize: 9, marginTop: 4 },
  menuSubtitlePrimary: { color: '#d2e1d5' },
  menuArrow: { color: GREEN, fontSize: 24, paddingHorizontal: 8 },
  menuArrowPrimary: { color: '#e6ece8' },
  builderPanel: { backgroundColor: '#101412', padding: 16, borderRadius: 8, borderWidth: 1, borderColor: '#26302b', marginBottom: 24 },
  builderLabel: { color: MUTED, fontSize: 8, fontWeight: '800', letterSpacing: 0.8 },
  detailLabel: { marginTop: 14 },
  cityStateRow: { flexDirection: 'row' },
  courseStatsGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 4, marginBottom: 14 },
  courseStat: { width: '50%', paddingVertical: 10, paddingRight: 10 },
  courseStatValue: { color: INK, fontFamily: 'Georgia', fontSize: 21, marginTop: 4 },
  courseStatNote: { color: MUTED, fontSize: 8, marginTop: 3 },
  roundCourseInfo: { marginTop: 18, padding: 14, borderRadius: 9, backgroundColor: '#101412', borderWidth: 1, borderColor: '#26302b' },
  roundCourseInfoHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  roundCourseInfoText: { color: INK, fontSize: 11, marginTop: 6 },
  roundCourseNotesLabel: { marginTop: 12 },
  roundCourseNotes: { color: INK, fontSize: 11, lineHeight: 17, marginTop: 5 },
  cityField: { flex: 1, marginRight: 12 },
  stateField: { width: 64 },
  notesInput: { height: 96, paddingTop: 10 },
  courseLinks: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 14 },
  courseLink: { height: 34, paddingHorizontal: 12, marginRight: 8, marginBottom: 8, borderRadius: 6, borderWidth: 1, borderColor: GREEN, alignItems: 'center', justifyContent: 'center' },
  courseLinkText: { color: GREEN, fontSize: 9, fontWeight: '800', letterSpacing: 0.6 },
  builderInput: { height: 43, borderBottomWidth: 1, borderBottomColor: '#26302b', color: INK, fontSize: 13, paddingHorizontal: 2, marginTop: 5 },
  primaryButton: { minHeight: 46, borderRadius: 7, backgroundColor: GREEN, alignItems: 'center', justifyContent: 'center', marginTop: 18 },
  disabledButton: { opacity: 0.5 },
  primaryButtonText: { color: '#e6ece8', fontSize: 9, fontWeight: '800', letterSpacing: 0.7 },
  builderSectionTitle: { color: INK, fontFamily: 'Georgia', fontSize: 18, marginBottom: 7 },
  courseItem: { minHeight: 62, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#26302b', paddingHorizontal: 7 },
  courseItemSelected: { backgroundColor: '#16231c' },
  courseItemSelect: { flex: 1, minHeight: 61, flexDirection: 'row', alignItems: 'center' },
  courseItemCopy: { flex: 1 },
  courseItemName: { color: INK, fontSize: 12, fontWeight: '700' },
  courseItemMeta: { color: MUTED, fontSize: 9, marginTop: 4 },
  courseSelectedMark: { color: GREEN, fontSize: 16, paddingHorizontal: 8 },
  deleteButton: { minHeight: 36, minWidth: 54, alignItems: 'center', justifyContent: 'center', marginLeft: 6 },
  deleteButtonText: { color: '#d07a68', fontSize: 8, fontWeight: '800', letterSpacing: 0.4 },
  deleteHoleButton: { minHeight: 34, alignSelf: 'flex-end', justifyContent: 'center', paddingHorizontal: 8, marginTop: 6 },
  mapEditor: { marginTop: 24, paddingTop: 18, borderTopWidth: 1, borderTopColor: '#26302b' },
  mapEditorHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  mapProgress: { color: GREEN, fontSize: 8, fontWeight: '800', letterSpacing: 0.5 },
  editorHoleNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 12 },
  holeNavButton: { width: 38, height: 36, borderWidth: 1, borderColor: '#26302b', borderRadius: 6, alignItems: 'center', justifyContent: 'center' },
  holeNavDisabled: { opacity: 0.35 },
  holeNavArrow: { color: GREEN, fontSize: 22, lineHeight: 25 },
  editorHoleCopy: { alignItems: 'center' },
  editorHoleName: { color: INK, fontSize: 10, fontWeight: '800', letterSpacing: 0.8 },
  editorHoleStatus: { color: MUTED, fontSize: 8, marginTop: 4 },
  markerTargetRow: { flexDirection: 'row', marginTop: 13, backgroundColor: '#151917', borderRadius: 7, padding: 3 },
  markerTarget: { flex: 1, height: 32, alignItems: 'center', justifyContent: 'center', borderRadius: 5 },
  markerTargetActive: { backgroundColor: '#101412' },
  markerTargetText: { color: MUTED, fontSize: 9, fontWeight: '700' },
  markerTargetTextActive: { color: GREEN, fontWeight: '800' },
  mapInstruction: { color: MUTED, fontSize: 9, marginTop: 10 },
  gpsPointCard: { padding: 12, marginTop: 9, borderWidth: 1, borderColor: '#26302b', borderRadius: 7, backgroundColor: '#101412' },
  gpsPointHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  gpsPointLabel: { color: INK, fontSize: 9, fontWeight: '800', letterSpacing: 0.6 },
  gpsPointState: { color: '#d39a6e', fontSize: 7, fontWeight: '800', letterSpacing: 0.4 },
  gpsPointSaved: { color: GREEN },
  gpsCoordinates: { color: INK, fontSize: 12, fontVariant: ['tabular-nums'], marginTop: 7 },
  gpsAccuracy: { color: MUTED, fontSize: 8, marginTop: 4 },
  holeDistance: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginTop: 10, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 7, backgroundColor: '#0f1a14' },
  parPicker: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10 },
  parOptions: { flexDirection: 'row' },
  parOption: { width: 40, height: 36, marginLeft: 6, borderRadius: 6, borderWidth: 1, borderColor: '#26302b', alignItems: 'center', justifyContent: 'center' },
  parOptionSelected: { backgroundColor: GREEN, borderColor: GREEN },
  parOptionText: { color: INK, fontFamily: 'Georgia', fontSize: 16 },
  parOptionTextSelected: { color: '#e6ece8' },
  holeDistanceLabel: { color: GREEN, fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  holeDistanceValue: { color: INK, fontFamily: 'Georgia', fontSize: 20, fontVariant: ['tabular-nums'] },
  gpsMessage: { color: GREEN, fontSize: 12, lineHeight: 17, marginTop: 10 },
  holeWizard: { flex: 1, paddingHorizontal: 23, paddingBottom: 14 },
  wizardProgress: { height: 38, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  wizardMappedCount: { marginTop: 4 },
  satelliteFrame: { flex: 1, minHeight: 230, marginTop: 6, borderRadius: 8, overflow: 'hidden', backgroundColor: '#0d1410', position: 'relative' },
  satelliteMap: { ...StyleSheet.absoluteFill },
  satelliteBadge: { position: 'absolute', top: 11, left: 11, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 5, backgroundColor: 'rgba(24,35,31,0.82)' },
  satelliteBadgeText: { color: '#e6ece8', fontSize: 8, fontWeight: '800', letterSpacing: 0.6 },
  recenterButton: { position: 'absolute', top: 10, right: 10, paddingHorizontal: 10, paddingVertical: 8, borderRadius: 5, backgroundColor: '#101412' },
  recenterButtonText: { color: INK, fontSize: 8, fontWeight: '800' },
  mapScaleBadge: { position: 'absolute', left: 11, bottom: 11, minWidth: 120, paddingHorizontal: 9, paddingVertical: 8, borderRadius: 5, backgroundColor: 'rgba(0,0,0,0.75)' },
  mapScaleRule: { height: 4, maxWidth: '100%', borderBottomWidth: 2, borderLeftWidth: 1, borderRightWidth: 1, borderColor: INK, marginBottom: 4 },
  mapScaleLabel: { color: INK, fontSize: 8, fontWeight: '800' },
  mapScaleWidth: { color: MUTED, fontSize: 7, fontWeight: '700', marginTop: 2 },
  mapUnavailable: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: '#0f1a14' },
  mapUnavailableTitle: { color: INK, fontFamily: 'Georgia', fontSize: 17, textAlign: 'center' },
  mapUnavailableText: { color: MUTED, fontSize: 12, lineHeight: 17, textAlign: 'center', marginTop: 8 },
  captureButtons: { flexDirection: 'row', marginTop: 10 },
  captureButton: { flex: 1, minHeight: 78, paddingHorizontal: 9, paddingVertical: 10, borderRadius: 7, borderWidth: 1, borderColor: '#26302b', backgroundColor: '#101412', marginRight: 8 },
  captureButtonSaved: { borderColor: GREEN, backgroundColor: '#16231c' },
  captureButtonLabel: { color: INK, fontSize: 9, fontWeight: '800', letterSpacing: 0.7 },
  captureButtonValue: { color: GREEN, fontSize: 8, fontWeight: '800', marginTop: 5 },
  captureButtonCoords: { color: MUTED, fontSize: 8, marginTop: 5, fontVariant: ['tabular-nums'] },
  wizardNavigation: { flexDirection: 'row', marginTop: 9 },
  wizardNavButton: { flex: 1, minHeight: 42, borderWidth: 1, borderColor: '#26302b', borderRadius: 6, alignItems: 'center', justifyContent: 'center', marginRight: 7 },
  wizardNavNext: { backgroundColor: GREEN, borderColor: GREEN, marginRight: 0, marginLeft: 7 },
  wizardNavText: { color: MUTED, fontSize: 8, fontWeight: '800', letterSpacing: 0.4 },
  wizardNavNextText: { color: '#e6ece8' },
  wizardNavFinish: { marginRight: 0, borderColor: GREEN },
  wizardNavFinishText: { color: GREEN, fontSize: 8, fontWeight: '800', letterSpacing: 0.4 },
  builderHint: { color: MUTED, fontSize: 9, marginTop: 8 },
  parEditorHeading: { marginTop: 22 },
  parRow: { minHeight: 56, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#26302b' },
  parStepButton: { width: 36, height: 36, borderRadius: 6, borderWidth: 1, borderColor: '#26302b', alignItems: 'center', justifyContent: 'center' },
  parStepText: { color: GREEN, fontSize: 18, fontWeight: '600' },
  parStepValue: { width: 38, textAlign: 'center', color: INK, fontFamily: 'Georgia', fontSize: 18 },
  addHoleButton: { height: 42, marginTop: 12, borderRadius: 6, borderWidth: 1, borderColor: GREEN, alignItems: 'center', justifyContent: 'center' },
  addHoleButtonText: { color: GREEN, fontSize: 9, fontWeight: '800', letterSpacing: 0.8 },
  secondaryStart: { marginTop: 19, minHeight: 44, borderWidth: 1, borderColor: GREEN, borderRadius: 7, alignItems: 'center', justifyContent: 'center' },
  secondaryStartText: { color: GREEN, fontSize: 9, fontWeight: '800', letterSpacing: 0.6 },
  builderFootnote: { color: '#6b766f', fontSize: 9, lineHeight: 14, marginTop: 11 },
  addDiscRow: { flexDirection: 'row', alignItems: 'center', marginTop: 3 },
  discInput: { flex: 1, marginRight: 12 },
  discResults: { marginTop: 10, borderTopWidth: 1, borderTopColor: '#26302b' },
  discResult: { minHeight: 52, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#26302b' },
  discResultCopy: { flex: 1, marginRight: 8 },
  discResultFlight: { color: INK, fontSize: 10, fontWeight: '700', fontVariant: ['tabular-nums'] },
  discResultsNote: { color: MUTED, fontSize: 10, lineHeight: 15, paddingVertical: 10 },
  discResultsCredit: { color: MUTED, fontSize: 7, fontWeight: '700', letterSpacing: 0.5, marginTop: 8 },
  addDiscButton: { height: 34, minWidth: 56, paddingHorizontal: 13, backgroundColor: GREEN, borderRadius: 5, alignItems: 'center', justifyContent: 'center' },
  addDiscButtonText: { color: '#e6ece8', fontSize: 9, fontWeight: '800' },
  practiceIntro: { backgroundColor: '#0f1a14', borderRadius: 9, padding: 18, marginBottom: 17 },
  practiceIntroTitle: { color: INK, fontFamily: 'Georgia', fontSize: 20, marginTop: 9 },
  practiceIntroCopy: { color: MUTED, fontSize: 10, lineHeight: 15, marginTop: 6 },
  practiceChoice: { minHeight: 67, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#26302b', paddingHorizontal: 8 },
  practiceChoiceSelected: { backgroundColor: '#16231c' },
  practiceChoiceCopy: { flex: 1 },
  practiceChoiceTitle: { color: INK, fontFamily: 'Georgia', fontSize: 16 },
  practiceChoiceSubtitle: { color: MUTED, fontSize: 9, marginTop: 4 },
  practiceChoiceMark: { color: GREEN, fontSize: 16, paddingHorizontal: 9 },
  courseLabel: { flex: 1, paddingRight: 10 },
  courseLabelName: { color: INK, fontSize: 12, fontWeight: '700', marginTop: 4 },
  roundToolbar: { height: 45, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modeSwitch: { flexDirection: 'row', backgroundColor: '#151917', borderRadius: 8, padding: 3 },
  modeOption: { paddingHorizontal: 13, paddingVertical: 7, borderRadius: 6 },
  modeSelected: { backgroundColor: '#101412' },
  modeText: { color: MUTED, fontSize: 10, fontWeight: '700' },
  modeTextSelected: { color: INK },
  holeSelector: { alignItems: 'center' },
  roundHoleNav: { flexDirection: 'row', alignItems: 'center' },
  roundHoleArrow: { width: 34, height: 40, borderWidth: 1, borderColor: '#26302b', borderRadius: 6, alignItems: 'center', justifyContent: 'center', marginHorizontal: 8 },
  holeLabel: { color: MUTED, fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  holeNumber: { color: INK, fontFamily: 'Georgia', fontSize: 20 },
  holeTotal: { color: MUTED, fontFamily: 'Arial', fontSize: 11 },
  chevron: { color: GREEN, fontFamily: 'Arial', fontSize: 12 },
  sectionTitle: { color: INK, fontFamily: 'Georgia', fontSize: 18 },
  scoreStrip: { flexDirection: 'row', backgroundColor: '#0f1a14', borderRadius: 8, paddingVertical: 7, paddingHorizontal: 4, marginTop: 6, marginBottom: 10 },
  scoreStripItem: { flex: 1, alignItems: 'center' },
  scoreStripLabel: { color: MUTED, fontSize: 10, fontWeight: '800', letterSpacing: 0.2 },
  scoreStripValue: { color: INK, fontFamily: 'Georgia', fontSize: 16, marginTop: 2, fontVariant: ['tabular-nums'] },
  roundMapFrame: { height: 300, marginTop: 0, marginBottom: 17, borderRadius: 9, overflow: 'hidden', backgroundColor: '#0d1410', position: 'relative' },
  shotMarker: { width: 22, height: 22, borderRadius: 12, borderWidth: 2, borderColor: '#fff', backgroundColor: '#b8622c', alignItems: 'center', justifyContent: 'center' },
  shotPinText: { color: '#e6ece8', fontSize: 9, fontWeight: '900' },
  boardCaption: { position: 'absolute', bottom: 11, left: 12, right: 12, flexDirection: 'row', justifyContent: 'space-between' },
  boardCaptionText: { color: '#7d8981', fontSize: 9, fontWeight: '800', letterSpacing: 0.7 },
  boardScale: { color: '#6b766f', fontSize: 9, fontWeight: '700' },
  basketDistances: { flexDirection: 'column', alignItems: 'stretch' },
  basketDistanceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', paddingVertical: 2 },
  roundHoleDistance: { marginTop: -5, marginBottom: 15 },
  logThrowButton: { minHeight: 64, backgroundColor: '#b8622c', borderRadius: 9, alignItems: 'center', justifyContent: 'center', paddingVertical: 10 },
  logThrowButtonText: { color: '#e6ece8', fontSize: 13, fontWeight: '900', letterSpacing: 1.2 },
  logThrowButtonHint: { color: '#f3dccb', fontSize: 12, marginTop: 4, textAlign: 'center', paddingHorizontal: 16 },
  sheetBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.65)' },
  sheet: { backgroundColor: PAPER, borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 20, paddingBottom: 34, width: '100%', maxWidth: 560, alignSelf: 'center' },
  sheetDistance: { color: GREEN, fontSize: 11, fontWeight: '700', marginTop: -4, marginBottom: 16 },
  sheetOptions: { flexDirection: 'row', flexWrap: 'wrap', paddingTop: 9 },
  sheetChip: { height: 40, marginBottom: 8, paddingHorizontal: 14 },
  sheetTypeButton: { height: 46 },
  lieGrid: { flexWrap: 'wrap', marginRight: -7 },
  // Four per row.
  styleButton: { flex: 0, width: '22.5%', marginBottom: 7, paddingHorizontal: 2 },
  lieButton: { flex: 0, width: '31%', marginBottom: 7 },
  obButton: { borderColor: '#6e3b31' },
  obText: { color: '#d07a68' },
  obPenaltyText: { color: '#d07a68', fontSize: 11, fontWeight: '800', marginTop: 2 },
  qualityButton: { height: 58 },
  qualityValue: { color: INK, fontFamily: 'Georgia', fontSize: 19 },
  qualityLabel: { color: MUTED, fontSize: 11, fontWeight: '700', marginTop: 2 },
  sheetFooter: { flexDirection: 'row-reverse', justifyContent: 'space-between', marginTop: 18 },
  pickerSheet: { maxHeight: '80%' },
  // The throw log sheet scrolls its options when they don't fit.
  logSheet: { maxHeight: '92%' },
  // The log sheet shows every option at once, so its buttons are a little shorter than elsewhere.
  logChip: { height: 34, marginBottom: 6, paddingHorizontal: 13 },
  logButton: { height: 38 },
  logQualityButton: { height: 46 },
  // A throw waiting below the map for its location to be saved.
  pendingThrow: { marginTop: 4 },
  pendingActions: { flexDirection: 'row', gap: 8, marginTop: 4 },
  pendingAction: { flex: 1 },
  pickerList: { flexGrow: 0 },
  sheetFooterButton: { borderWidth: 1, borderColor: '#26302b', borderRadius: 5, paddingHorizontal: 14, paddingVertical: 10 },
  controlHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  controlTitle: { color: INK, fontFamily: 'Georgia', fontSize: 17 },
  controlStep: { color: MUTED, fontSize: 11, fontWeight: '800', letterSpacing: 0.8 },
  fieldLabel: { color: MUTED, fontSize: 11, fontWeight: '800', letterSpacing: 0.9 },
  chipRow: { flexDirection: 'row', paddingTop: 7, paddingBottom: 2 },
  chip: { paddingHorizontal: 12, height: 30, borderRadius: 6, borderWidth: 1, borderColor: '#26302b', marginRight: 7, justifyContent: 'center' },
  chipSelected: { backgroundColor: GREEN, borderColor: GREEN },
  chipText: { color: '#a9b4ad', fontSize: 12, fontWeight: '700' },
  chipTextSelected: { color: '#e6ece8' },
  typeLabel: { marginTop: 9 },
  typeRow: { flexDirection: 'row', marginTop: 7 },
  typeButton: { flex: 1, height: 31, borderRadius: 6, borderWidth: 1, borderColor: '#26302b', alignItems: 'center', justifyContent: 'center', marginRight: 7 },
  typeButtonSelected: { backgroundColor: '#2a1d12', borderColor: '#7a5634' },
  typeText: { color: '#a9b4ad', fontSize: 12, fontWeight: '700' },
  typeTextSelected: { color: '#e0a070' },
  latestRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#26302b' },
  latestEyebrow: { color: MUTED, fontSize: 11, fontWeight: '800', letterSpacing: 0.8 },
  latestText: { color: INK, fontSize: 11, fontWeight: '600', marginTop: 4 },
  undoButton: { borderWidth: 1, borderColor: '#26302b', borderRadius: 5, paddingHorizontal: 10, paddingVertical: 7 },
  undoText: { color: MUTED, fontSize: 12, fontWeight: '800' },
  finishButton: { height: 46, backgroundColor: GREEN, borderRadius: 7, marginTop: 12, alignItems: 'center', justifyContent: 'center' },
  dimToggleText: { color: MUTED, fontSize: 12, fontWeight: '800', letterSpacing: 1 },
  gpsWarning: { color: '#d07a68', fontSize: 12, lineHeight: 17, marginTop: -10, marginBottom: 14 },
  endSessionButton: { height: 42, borderRadius: 7, borderWidth: 1, borderColor: '#26302b', marginTop: 8, alignItems: 'center', justifyContent: 'center' },
  endSessionText: { color: '#d07a68', fontSize: 12, fontWeight: '800', letterSpacing: 1 },
  finishButtonText: { color: '#e6ece8', fontSize: 12, fontWeight: '800', letterSpacing: 1 },
  finishArrow: { fontSize: 14 },
  footnote: { textAlign: 'center', color: MUTED, fontSize: 11, marginTop: 10, marginBottom: 2 },
  bottomBar: { height: 36, borderTopWidth: 1, borderTopColor: '#26302b', paddingHorizontal: 23, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  bottomStatus: { color: MUTED, fontSize: 7, fontWeight: '800', letterSpacing: 0.7 },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#6f9a68', marginRight: 5 },
  bottomCount: { color: MUTED, fontSize: 7, fontWeight: '800' },
  insightHero: { marginTop: 6, padding: 20, backgroundColor: '#0f1a14', borderRadius: 9 },
  insightEyebrow: { color: GREEN, fontSize: 8, fontWeight: '800', letterSpacing: 1 },
  insightNumber: { color: INK, fontFamily: 'Georgia', fontSize: 48, marginTop: 10 },
  insightUnit: { color: MUTED, fontFamily: 'Arial', fontSize: 16 },
  insightCaption: { color: MUTED, fontSize: 9, fontWeight: '600' },
  sparkline: { height: 105, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 13, paddingHorizontal: 4 },
  sparkBar: { width: '10%', backgroundColor: '#6b9b73', borderTopLeftRadius: 4, borderTopRightRadius: 4 },
  sparkLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  finalScore: { backgroundColor: '#0f1a14', borderRadius: 9, padding: 18, marginTop: 1, marginBottom: 20 },
  finalScoreRow: { flexDirection: 'row', alignItems: 'baseline', marginTop: 6 },
  finalScoreValue: { color: INK, fontFamily: 'Georgia', fontSize: 44 },
  finalScoreToPar: { color: INK, fontFamily: 'Georgia', fontSize: 26, marginLeft: 12 },
  underPar: { color: GREEN },
  overPar: { color: '#d9884e' },
  resultChips: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
  resultChip: { backgroundColor: '#101412', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 5, marginRight: 6, marginBottom: 6 },
  resultChipText: { color: INK, fontSize: 9, fontWeight: '700' },
  scorecard: { marginTop: 8, marginBottom: 22, borderRadius: 9, borderWidth: 1, borderColor: '#26302b', backgroundColor: '#101412', overflow: 'hidden' },
  scorecardRow: { flexDirection: 'row', alignItems: 'center', minHeight: 38, borderBottomWidth: 1, borderBottomColor: '#26302b' },
  scorecardHeader: { minHeight: 32, backgroundColor: '#141816' },
  scorecardTotal: { borderBottomWidth: 0, backgroundColor: '#141816' },
  scorecardCell: { flex: 1, textAlign: 'center', color: INK, fontSize: 12, fontVariant: ['tabular-nums'] },
  scorecardHoleCell: { textAlign: 'left', paddingLeft: 14 },
  scorecardHeaderText: { color: MUTED, fontSize: 8, fontWeight: '800', letterSpacing: 0.7 },
  scorecardScore: { fontWeight: '800' },
  throwByThrowTitle: { marginBottom: 4 },
  sessionModeTag: { color: GREEN, fontSize: 7, fontWeight: '800', letterSpacing: 0.6, marginRight: 8 },
  roundHole: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#26302b' },
  roundHoleHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 6 },
  roundHoleMapToggle: { color: GREEN, fontFamily: 'Arial', fontSize: 8, fontWeight: '800', letterSpacing: 0.6 },
  roundHoleMap: { height: 260, marginTop: 4, marginBottom: 10, borderRadius: 9, overflow: 'hidden', backgroundColor: '#0d1410' },
  scorecardRowActive: { backgroundColor: '#0f1a14' },
  obMarker: { backgroundColor: '#a55343' },
  // A throw on the hole-history map, colored by type; there are too many to number.
  throwDot: { width: 12, height: 12, borderRadius: 6, borderWidth: 1.5, borderColor: '#000' },
  mapLegend: { color: MUTED, fontSize: 12, marginTop: -4, marginBottom: 6 },
  roundHoleTitle: { color: INK, fontFamily: 'Georgia', fontSize: 16 },
  roundHoleMeta: { color: GREEN, fontSize: 8, fontWeight: '800', letterSpacing: 0.6 },
  roundThrow: { color: MUTED, fontSize: 10, lineHeight: 17 },
  statsGrid: { flexDirection: 'row', marginTop: 12, marginBottom: 25 },
  statBlock: { flex: 1, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#26302b' },
  statLabel: { color: MUTED, fontSize: 8, fontWeight: '800', letterSpacing: 0.7 },
  statValue: { color: INK, fontFamily: 'Georgia', fontSize: 23, marginTop: 7 },
  discStat: { flexDirection: 'row', alignItems: 'center', height: 48, borderBottomWidth: 1, borderBottomColor: '#26302b' },
  discStatName: { width: 82, color: INK, fontSize: 10, fontWeight: '700' },
  discStatTrack: { flex: 1, height: 5, backgroundColor: '#1a1f1c', borderRadius: 4, overflow: 'hidden' },
  discStatFill: { height: 5, backgroundColor: '#6c9a72', borderRadius: 4 },
  discStatValue: { width: 51, textAlign: 'right', color: MUTED, fontSize: 9, fontWeight: '700' },
  bagIntro: { backgroundColor: '#0f1a14', padding: 20, borderRadius: 9, marginTop: 6, marginBottom: 15 },
  bagHeadline: { color: INK, fontFamily: 'Georgia', fontSize: 28, marginTop: 10 },
  bagBody: { color: MUTED, fontSize: 11, lineHeight: 17, marginTop: 6 },
  bagItem: { minHeight: 67, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#26302b', paddingHorizontal: 4 },
  bagItemSelect: { flex: 1, minHeight: 66, flexDirection: 'row', alignItems: 'center' },
  bagItemSelected: { backgroundColor: '#16231c' },
  discSwatch: { width: 39, height: 39, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  discSwatchText: { color: '#e6ece8', fontSize: 12, fontWeight: '900' },
  bagItemCopy: { marginLeft: 12, flex: 1 },
  bagItemName: { color: INK, fontSize: 12, fontWeight: '800' },
  bagItemMeta: { color: MUTED, fontSize: 9, marginTop: 4 },
  bagArrow: { color: GREEN, fontSize: 17, paddingHorizontal: 9 },
});

// Feedback while a hold-to-press button is held down.
export const holdStyles = StyleSheet.create({ holding: { opacity: 0.55 } });
